---
#------------------------------------------------
# GitHub Actions Part-1 - Basics
# Copyleft (c) by My 2025
#------------------------------------------------
name: My-GithubActions-Basics

on:
  push:
    branches:
      - "main"

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello World from Testing job"

  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello World from Deploy job"
