---
#------------------------------------------------
# GitHub Actions Part-1 - Basics
# Copyleft (c) by My 2025
#------------------------------------------------
name: My-GithubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - "main"

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello World from Testing job"
      - name: Execute few command
        run: |
          echo "Hello Message1"
          echo "Hello Message1"
          echo "Application name: ${{env.APPLICATION_NAME}}"
      - name: List current folder
        run: ls -la

      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: List current folder
        run: ls -la

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job Level Variable1"
      VAR2: "This is Job Level Variable2"
    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello World from Deploy job"
      - name: Print env vars
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is Super local Environment variable"

      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Lets test some packages if the are here 1
        run: aws --version

      - name: Lets test some packages if the are here 2
        run: zip --version
